version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.61.0
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Tehran
      - TZ=Asia/Tehran
    volumes:
      - ./n8n-data:/home/node/.n8n